/**
 * Browser chat route for Managed Agents.
 * Streams one turn directly from `runManagedAgent()`.
 *
 * @module app/api/chat/route
 */
import { createUIMessageStreamResponse } from "ai";
import { z } from "zod";

import { authenticateRequest, jsonError } from "@/lib/api/route-helpers";
import { allowedModelIds, DEFAULT_CHAT_MODEL } from "@/lib/ai/models";
import { resolveClientId } from "@/lib/chat/client-id";
import { extractUserInput } from "@/lib/chat/extract-user-input";
import {
  resumeManagedAgentFromApproval,
  runManagedAgent,
} from "@/lib/managed-agents/adapter";
import { getAnthropicClient } from "@/lib/managed-agents/anthropic-client";
import { checkRateLimit } from "@/lib/rate-limit";

export const runtime = "nodejs";
export const maxDuration = 300;

const requestSchema = z.object({
  id: z.string().min(1),
  messages: z
    .array(
      z.object({
        id: z.string().optional(),
        role: z.string(),
        parts: z.array(z.unknown()).optional(),
      }),
    )
    .min(1),
  selectedChatModel: z.string().optional(),
});

interface ApprovalContinuation {
  approvalId: string;
  approved: boolean;
  denyMessage?: string;
}

/**
 * Checks the trailing messages for a tool approval response generated by useChat.
 */
function extractApprovalContinuation(
  messages: Array<{ parts?: unknown[] }>,
): ApprovalContinuation | null {
  const startIndex = Math.max(0, messages.length - 2);

  for (let index = messages.length - 1; index >= startIndex; index -= 1) {
    const message = messages[index];
    for (const part of message.parts ?? []) {
      if (typeof part !== "object" || part === null || !("type" in part)) {
        continue;
      }

      const typedPart = part as Record<string, unknown>;
      if (typedPart.type !== "tool-invocation") {
        continue;
      }

      const state =
        typeof typedPart.state === "string" ? typedPart.state : null;
      if (state !== "approval-responded" && state !== "output-denied") {
        continue;
      }

      const approvalId =
        typeof typedPart.toolCallId === "string" ? typedPart.toolCallId : null;
      if (!approvalId) {
        continue;
      }

      const approval =
        typeof typedPart.approval === "object" && typedPart.approval !== null
          ? (typedPart.approval as { approved?: boolean; denyMessage?: string })
          : undefined;

      return {
        approvalId,
        approved: state !== "output-denied" && approval?.approved === true,
        ...(typeof approval?.denyMessage === "string"
          ? { denyMessage: approval.denyMessage }
          : {}),
      };
    }
  }

  return null;
}

/**
 * Accepts one browser chat turn and streams the managed-agent response.
 */
export async function POST(request: Request): Promise<Response> {
  const parsedBody = requestSchema.safeParse(await request.json().catch(() => null));
  if (!parsedBody.success) {
    return jsonError("Invalid request body.", 400);
  }

  const auth = await authenticateRequest();
  if (auth.kind === "error") {
    return auth.response;
  }

  const { allowed, retryAfter } = await checkRateLimit(`chat:${auth.userId}`, 30, 60);
  if (!allowed) {
    return new Response(
      JSON.stringify({
        error: "Rate limit exceeded. Please wait before sending more messages.",
      }),
      {
        status: 429,
        headers: {
          "Content-Type": "application/json",
          "Retry-After": String(retryAfter ?? 60),
        },
      },
    );
  }

  const selectedChatModel = parsedBody.data.selectedChatModel ?? DEFAULT_CHAT_MODEL;
  if (!allowedModelIds.has(selectedChatModel)) {
    return jsonError("Invalid selected chat model.", 400);
  }

  const approval = extractApprovalContinuation(parsedBody.data.messages);
  if (approval) {
    const result = await resumeManagedAgentFromApproval({
      anthropic: getAnthropicClient(),
      supabase: auth.supabase,
      clientId: await resolveClientId(auth.supabase, auth.userId),
      approvalId: approval.approvalId,
      approved: approval.approved,
      denyMessage: approval.denyMessage,
    });

    if (result.status === "missing") {
      return jsonError("Approval not found.", 404);
    }

    if (result.status === "already_resolved") {
      return jsonError("Approval already resolved.", 409);
    }

    if (result.status === "error") {
      return jsonError(result.error, 500);
    }

    return createUIMessageStreamResponse({ stream: result.stream as never });
  }

  const clientId = await resolveClientId(auth.supabase, auth.userId);
  const lastMessage = parsedBody.data.messages[parsedBody.data.messages.length - 1];
  const { text, fileParts } = extractUserInput({
    parts: lastMessage.parts ?? [],
  });
  if (!text && fileParts.length === 0) {
    return jsonError("Message must contain text or files.", 400);
  }

  const { data: existingThread, error: threadLookupError } = await auth.supabase
    .from("conversation_threads")
    .select("thread_id, title")
    .eq("thread_id", parsedBody.data.id)
    .eq("client_id", clientId)
    .eq("is_archived", false)
    .maybeSingle();
  if (threadLookupError) {
    return jsonError("Failed to process request.", 500);
  }

  let threadTitle: string | null = null;
  if (!existingThread) {
    const { error: insertError } = await auth.supabase
      .from("conversation_threads")
      .insert({
        thread_id: parsedBody.data.id,
        client_id: clientId,
        title: null,
      });
    if (insertError) {
      return jsonError("Failed to create thread.", 500);
    }
  } else {
    threadTitle = existingThread.title;
  }

  const { data: clientContext } = await auth.supabase
    .from("clients")
    .select("client_profile, user_preferences")
    .eq("client_id", clientId)
    .single();

  const stream = await runManagedAgent({
    anthropic: getAnthropicClient(),
    supabase: auth.supabase,
    clientId,
    threadId: parsedBody.data.id,
    input: text ?? "",
    fileParts,
    userMessageSourceId: lastMessage.id,
    clientProfile: clientContext?.client_profile ?? null,
    userPreferences: clientContext?.user_preferences ?? null,
    threadTitle,
    selectedChatModel,
  });

  return createUIMessageStreamResponse({ stream: stream as never });
}
