/**
 * Shared semantic icon registry for the product shell and dashboard surfaces.
 * Uses lucide-react as the single icon library (shadcn default).
 * @module components/icons/app-icons
 */
import type { LucideIcon, LucideProps } from "lucide-react";
import {
  PlusIcon,
  BriefcaseIcon,
  ArchiveIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpRightIcon,
  ZapIcon,
  BellRingIcon,
  Building2Icon,
  GlobeIcon as BrowserIcon,
  CalendarIcon,
  RadioIcon,
  MessageCircleIcon,
  CheckIcon,
  CheckCheckIcon,
  ChevronDownIcon,
  HeartHandshakeIcon,
  XIcon,
  UsersIcon,
  ClockIcon,
  BookUserIcon,
  LayoutDashboardIcon,
  BanknoteIcon,
  FileTextIcon,
  FoldersIcon,
  DownloadIcon,
  MailIcon,
  FlameIcon,
  FolderOpenIcon,
  ClipboardListIcon,
  GlobeIcon,
  HomeIcon,
  ChartBarIcon,
  PlugIcon,
  KanbanIcon,
  BookOpenTextIcon,
  LinkIcon,
  LockIcon,
  LogOutIcon,
  MapPinIcon,
  BotMessageSquareIcon,
  MicIcon,
  StickyNoteIcon,
  PhoneIcon,
  PlayIcon,
  SearchIcon,
  ChevronsUpDownIcon,
  SendIcon,
  SettingsIcon,
  Share2Icon,
  ShieldCheckIcon,
  PenLineIcon,
  MegaphoneIcon,
  TableIcon,
  ListChecksIcon,
  UploadIcon,
  EyeIcon,
  BookOpenIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  EllipsisIcon,
  CircleUserIcon,
  CrosshairIcon,
} from "lucide-react";

import { cn } from "@/lib/utils";

export const appIcons = {
  add: PlusIcon,
  agency: BriefcaseIcon,
  archive: ArchiveIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowUpRight: ArrowUpRightIcon,
  automations: ZapIcon,
  bell: BellRingIcon,
  building: Building2Icon,
  browser: BrowserIcon,
  calendar: CalendarIcon,
  channels: RadioIcon,
  chat: MessageCircleIcon,
  check: CheckIcon,
  checks: CheckCheckIcon,
  chevronDown: ChevronDownIcon,
  clientCare: HeartHandshakeIcon,
  close: XIcon,
  contacts: UsersIcon,
  clock: ClockIcon,
  crm: BookUserIcon,
  dashboard: LayoutDashboardIcon,
  deals: BanknoteIcon,
  document: FileTextIcon,
  documents: FoldersIcon,
  download: DownloadIcon,
  email: MailIcon,
  flame: FlameIcon,
  folderOpen: FolderOpenIcon,
  form: ClipboardListIcon,
  globe: GlobeIcon,
  home: HomeIcon,
  insights: ChartBarIcon,
  integrations: PlugIcon,
  kanban: KanbanIcon,
  knowledge: BookOpenTextIcon,
  leadGen: MegaphoneIcon,
  link: LinkIcon,
  lock: LockIcon,
  logout: LogOutIcon,
  mapPin: MapPinIcon,
  message: MessageCircleIcon,
  missionControl: CrosshairIcon,
  microphone: MicIcon,
  money: BanknoteIcon,
  more: EllipsisIcon,
  note: StickyNoteIcon,
  outputs: BotMessageSquareIcon,
  person: CircleUserIcon,
  phone: PhoneIcon,
  play: PlayIcon,
  property: Building2Icon,
  schedule: CalendarClockIcon,
  search: SearchIcon,
  selector: ChevronsUpDownIcon,
  send: SendIcon,
  settings: SettingsIcon,
  share: Share2Icon,
  shield: ShieldCheckIcon,
  signature: PenLineIcon,
  social: Share2Icon,
  table: TableIcon,
  tasks: ListChecksIcon,
  upload: UploadIcon,
  viewing: EyeIcon,
  whatsapp: MessageCircleIcon,
  workspace: FoldersIcon,
  knowledgeFile: BookOpenIcon,
  meeting: CalendarDaysIcon,
  agent: BotMessageSquareIcon,
  compose: PenLineIcon,
  area: MapPinIcon,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof appIcons;

interface AppIconProps extends LucideProps {
  name: AppIconName;
}

/**
 * Renders a semantic app icon with shared accessibility and sizing defaults.
 */
export function AppIcon({ name, className, ...props }: AppIconProps) {
  const Icon = appIcons[name];

  return <Icon aria-hidden="true" className={cn("shrink-0", className)} {...props} />;
}
