/**
 * Shared semantic icon registry for the product shell and dashboard surfaces.
 * It keeps high-visibility app icons on one consistent Tabler line style.
 * @module components/icons/app-icons
 */
import type { IconBaseProps, IconType } from "react-icons";
import {
  TbAddressBook,
  TbArchive,
  TbArrowLeft,
  TbArrowRight,
  TbArrowUpRight,
  TbBellRinging2,
  TbBolt,
  TbBook2,
  TbBooks,
  TbBrain,
  TbBrowser,
  TbBrandWhatsapp,
  TbBriefcase,
  TbBroadcast,
  TbCalendar,
  TbCalendarClock,
  TbCalendarEvent,
  TbCashBanknote,
  TbChartBar,
  TbCheck,
  TbChecks,
  TbChevronDown,
  TbChecklist,
  TbClipboardList,
  TbClock,
  TbDots,
  TbDownload,
  TbEye,
  TbFileText,
  TbFlame,
  TbFolderOpen,
  TbFolders,
  TbGlobe,
  TbHeartHandshake,
  TbHome,
  TbLayoutDashboard,
  TbLayoutKanban,
  TbLink,
  TbLock,
  TbLogout2,
  TbMail,
  TbMapPin,
  TbMessage2Cog,
  TbMessageCircle,
  TbMicrophone2,
  TbNotes,
  TbPhone,
  TbPlayerPlay,
  TbPlugConnected,
  TbPlus,
  TbSearch,
  TbSelector,
  TbSettings,
  TbShare2,
  TbShieldCheck,
  TbSignature,
  TbSpeakerphone,
  TbTable,
  TbTargetArrow,
  TbUpload,
  TbUserCircle,
  TbUsersGroup,
  TbSend,
  TbX,
  TbBuilding,
} from "react-icons/tb";

import { cn } from "@/lib/utils";

export const appIcons = {
  add: TbPlus,
  agency: TbBriefcase,
  archive: TbArchive,
  arrowLeft: TbArrowLeft,
  arrowRight: TbArrowRight,
  arrowUpRight: TbArrowUpRight,
  automations: TbBolt,
  bell: TbBellRinging2,
  building: TbBuilding,
  browser: TbBrowser,
  calendar: TbCalendar,
  channels: TbBroadcast,
  chat: TbMessageCircle,
  check: TbCheck,
  checks: TbChecks,
  chevronDown: TbChevronDown,
  clientCare: TbHeartHandshake,
  close: TbX,
  contacts: TbUsersGroup,
  clock: TbClock,
  crm: TbAddressBook,
  dashboard: TbLayoutDashboard,
  deals: TbCashBanknote,
  document: TbFileText,
  documents: TbFolders,
  download: TbDownload,
  email: TbMail,
  flame: TbFlame,
  folderOpen: TbFolderOpen,
  form: TbClipboardList,
  globe: TbGlobe,
  home: TbHome,
  insights: TbChartBar,
  integrations: TbPlugConnected,
  kanban: TbLayoutKanban,
  knowledge: TbBooks,
  leadGen: TbSpeakerphone,
  link: TbLink,
  lock: TbLock,
  logout: TbLogout2,
  mapPin: TbMapPin,
  memory: TbBrain,
  message: TbMessageCircle,
  missionControl: TbTargetArrow,
  microphone: TbMicrophone2,
  money: TbCashBanknote,
  more: TbDots,
  note: TbNotes,
  outputs: TbMessage2Cog,
  person: TbUserCircle,
  phone: TbPhone,
  play: TbPlayerPlay,
  property: TbBuilding,
  schedule: TbCalendarClock,
  search: TbSearch,
  selector: TbSelector,
  send: TbSend,
  settings: TbSettings,
  share: TbShare2,
  shield: TbShieldCheck,
  signature: TbSignature,
  social: TbShare2,
  table: TbTable,
  tasks: TbChecklist,
  upload: TbUpload,
  viewing: TbEye,
  whatsapp: TbBrandWhatsapp,
  workspace: TbFolders,
  knowledgeFile: TbBook2,
  meeting: TbCalendarEvent,
  area: TbMapPin,
} as const satisfies Record<string, IconType>;

export type AppIconName = keyof typeof appIcons;

interface AppIconProps extends IconBaseProps {
  name: AppIconName;
}

/**
 * Renders a semantic app icon with shared accessibility and sizing defaults.
 */
export function AppIcon({ name, className, ...props }: AppIconProps) {
  const Icon = appIcons[name];

  return <Icon aria-hidden="true" className={cn("shrink-0", className)} {...props} />;
}
