/**
 * Re-exports from lucide-react for backward compatibility.
 * All icons now come directly from lucide-react.
 * @module components/icons/lucide-compat
 */
export {
  CircleAlertIcon as AlertCircle,
  TriangleAlertIcon as AlertTriangle,
  ArrowDownIcon as ArrowDown,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowUpIcon as ArrowUp,
  ArrowUpDownIcon as ArrowUpDown,
  ChartBarIcon as BarChart3,
  BlocksIcon as Blocks,
  BrainIcon as Brain,
  Building2Icon as Building2,
  CalendarIcon as Calendar,
  CalendarIcon,
  CheckIcon as Check,
  CircleCheckIcon as CheckCircle,
  CircleCheckIcon as CheckCircle2,
  CircleCheckIcon as CheckCircleIcon,
  ChevronDownIcon as ChevronDown,
  ChevronRightIcon as ChevronRight,
  ChevronUpIcon as ChevronUp,
  CopyIcon as Copy,
  DatabaseIcon as Database,
  DownloadIcon as Download,
  ExternalLinkIcon as ExternalLink,
  FileSpreadsheetIcon as FileSpreadsheet,
  FileTextIcon as FileText,
  FileTypeIcon as FileType,
  FilterIcon as Filter,
  FolderIcon as Folder,
  GripVerticalIcon as GripVertical,
  InfoIcon as Info,
  LayersIcon as Layers,
  LayoutGridIcon as LayoutGrid,
  LightbulbIcon as Lightbulb,
  LinkIcon as Link,
  ListIcon as List,
  Loader2Icon as Loader2,
  LockIcon as Lock,
  MessageCircleIcon as MessageCircle,
  PaperclipIcon as Paperclip,
  PencilIcon as Pencil,
  PenToolIcon as PenTool,
  PlusIcon as Plus,
  PresentationIcon as Presentation,
  RefreshCwIcon as RefreshCw,
  RotateCcwIcon as RotateCcw,
  SearchIcon as Search,
  SendIcon as Send,
  Settings2Icon as Settings2,
  SparkleIcon as Sparkle,
  SparklesIcon as Sparkles,
  SquareTerminalIcon as SquareTerminal,
  Trash2Icon as Trash2,
  UploadIcon as Upload,
  XIcon as X,
  CircleXIcon as XCircleIcon,
} from "lucide-react";
